### ISSUE TITLE
Can't find pypng!

### ISSUE THREAD

**Issue by dxdpxl** [city96/ComfyUI_ColorMod#1]
Can't find pypng! Please install to enable 16bit image support.
Whatever install method I try, it can't find it.

**Comment by dxdpxl** [comment]
ComfyUI zip and installed via run_nvidia_gpu.bat on a custom drive (not C:)

python --version: Python 3.10.11

python -m pip show pypng:
Name: pypng
Version: 0.20220715.0
Summary: Pure Python library for saving and loading PNG images
Home-page: https://gitlab.com/drj11/pypng
Author: David Jones
Author-email: drj@pobox.com
License: MIT
Location: c:\users\admin\appdata\roaming\python\python310\site-packages
Requires:
Required-by:
PS C:\Users\admin>

**Comment by city96** [comment]
>Location: c:\users\admin\appdata\roaming\python\python310\site-packages

I think this might be the problem. You need to install it to the embedded python that came with your comfy install instead of the system one. You should be able to shift right click an empty space where your `run_nvidia_gpu.bat` is and then run `python_embeded\python.exe -m pip install pypng` to install it to the right python version.

**Comment by dxdpxl** [comment]
That was it! Amazing. Thanks! I had already read something about that, but couldn't manage it with embedded, I was "confused" about the location, lol. Now it's clear... I'm new to this, so forgive me. Thanks again, have a great night!

**Comment by city96** [comment]
No worries!
